### ISSUE TITLE
Migration won't create table even if abstract setting is set to false

### ISSUE THREAD

**Issue by ericswpark** [jkeifer/drf-chunked-upload#13]
Currently the `python manage.py migrate` command will not create a table for the `ChunkedUpload` model, even if the abstract setting is set to false.

Possibly related: https://docs.djangoproject.com/en/3.2/topics/migrations/#dependencies

**Comment by jkeifer** [comment]
Did you run `manage.py makemigrations drf_chunked_upload`?

**Comment by jkeifer** [comment]
I initially missed your comment on the previous issue, but I see now you did try `makemigrations`. I'm curious though, did you explicitly specify the `drf_chunked_upload` app name?

I am working on my tests and I have a test to make and apply the migrations, which _appears_ to work as expected (though using a transient test database, so I'll fully acknowledge the test could be overlooking something).

**Comment by ericswpark** [comment]
Oops, I didn't realize running just `manage.py migrate/makemigrations` without the app name specified only created/managed migrations for the current app. Sorry about that!

Running `manage.py makemigrations drf_chunked_upload` works, but it creates the migration file within Python's `site-packages` folder. I suppose I can move it outside to the main app's migration folder, but I'm not sure if that's how we're supposed to import migrations from libraries.

**Comment by ericswpark** [comment]
Yup, that doesn't work because the migration gets applied to the main app's table, not drf_chunked_upload's table, so it crashes on runtime. It looks like I'll have to just work around this issue by creating another model that inherits `ChunkedUpload`.

**Comment by jkeifer** [comment]
When you say

> it creates the migration file within Python's `site-packages` folder

do you mean the migration files are within the drf_chunked_upload package dir in the `site-packages` folder?

If so, then I think that I should have already made the migrations and have them in the package. Whether they are applied or not would be based on if you are using the abstract model or not. Then maintaining the migrations for changes to the concrete model would be on me, and you wouldn't need to run `makemigrations`.

That said, I think they would be applied just fine if indeed they are inside the drf_chunked_upload package dir. So if you don't move them do they apply correctly?

**Comment by ericswpark** [comment]
> When you say
> 
> > it creates the migration file within Python's `site-packages` folder
> 
> do you mean the migration files are within the drf_chunked_upload package dir in the `site-packages` folder?

Yes.

> If so, then I think that I should have already made the migrations and have them in the package. Whether they are applied or not would be based on if you are using the abstract model or not. Then maintaining the migrations for changes to the concrete model would be on me, and you wouldn't need to run `makemigrations`.

That would be great, but right now the migrations folder is empty in the library.

> That said, I think they would be applied just fine if indeed they are inside the drf_chunked_upload package dir. So if you don't move them do they apply correctly?


Unfortunately my Python project is packaged with Docker, so I can't ~~apply~~ (sorry, I mean create) any migrations within the `site-packages` folder. Trying to create the migrations within the Docker container gives me a permission error since the Python `site-packages` directory is read-only. I think if the library already had migrations built-in then I'd be able to apply them within the Docker container.

**Comment by jkeifer** [comment]
Hmm, okay. Let me see if I can get a new package version out with migrations you can try out. I'll let you know here once I have that done.

Thanks for all the feedback. I appreciate it as it makes the project better.

**Comment by ericswpark** [comment]
That would be great. Thank you so much and sorry for annoying you with all these tickets.

**Comment by jkeifer** [comment]
I pushed an alpha release 0.5.0a0 to pypi. I think you'll have to specify it by that version to get it, it will still pull the old version if you just use latest as it is pre-release. But let me know if that fixes the migration for you or if you have any other issues.

**Comment by ericswpark** [comment]
Hi, I downloaded release 0.5.0a0 but the migrations folder is blank?

<img width="315" alt="image" src="https://user-images.githubusercontent.com/13326074/118600459-fc1eb300-b7eb-11eb-9a5c-65a85099984d.png">

Also the management folder is gone as well. Maybe the setup.py config is excluding these files?

**Comment by jkeifer** [comment]
Dang, sorry about that. Not sure if that's due to changes in the build tooling or what, but I've resolved that error and uploaded a new version `0.5.0a1`. Thanks for hanging in there as I sort out all the new tooling I need to manage this package again.

**Comment by ericswpark** [comment]
@jkeifer thank you for the fix. I can confirm that the migration now works and the application no longer crashes.

I'm not sure why though, but the upload part isn't working properly for me. I followed the instructions in the README, and submitted my first chunk with a PUT request. The library gave me back a new URL, so I 'PUT' the second chunk to the returned URL. But the library responded with another URL that was different from the first URL. This kept happening for all chunks. And when I finally put in a POST request with the MD5 field to the last URL returned, it gave me an error of "No chunk file was submitted."

Looking at the admin panel, it seems like it created a chunked upload object for each chunk (!):

<img width="376" alt="image" src="https://user-images.githubusercontent.com/13326074/118698505-73376400-b84b-11eb-8f0b-584d9ef53700.png">

Here are the `urls.py` entries. Did I mess anything up here?

```python
    path('maintainers/api/chunked_upload/', ChunkedBuildUpload.as_view(), name='chunked_build_upload'),
    path('maintainers/api/chunked_upload/<uuid:pk>/', ChunkedBuildUpload.as_view(), name='chunkedupload-detail'),
```

**Comment by ericswpark** [comment]
Sorry, never mind. There was a problem with the uploader and it was creating extra chunk objects. My bad!

I'll submit a patch for the README since it appears to be out of date (some fields don't match, etc).

Again thank you so much for the help!
