### ISSUE TITLE
Stable release of 0.5.0?

### ISSUE THREAD

**Issue by ericswpark** [jkeifer/drf-chunked-upload#16]
Hi, when would the code in the `ci-test` branch be merged into `master`? No rush, but it's been nearly a month and I was wondering if the code would make it to a stable release. Thanks!

**Comment by jkeifer** [comment]
It will, I promise. The `ci-test` branch is still full of half-baked CI ideas that I need to get back to and clean up before it can be merged. Things have gotten pretty busy for me, but I expect to have enough time to get that done by the end of July, if not sooner. I hope that timeline is okay.

**Comment by ericswpark** [comment]
Ah, cool, thank you for the reply! Again, no pressure; just wanted to make sure the repo wasn't forgotten or anything.

**Comment by jkeifer** [comment]
@ericswpark I just pushed out a stable release of 0.5.0. It has a lot of changes in it, but it now has lots of tests, so I'm hoping you shouldn't notice any problems with all the refactoring and cleanup. If you do have any problems please let me know.

**Comment by ericswpark** [comment]
@jkeifer thank you so much! I'm integrating the changes in 0.5.0 into my project right now. I noticed the `on_completion()` code you proposed in #18 didn't make it in yet. Do you want me to make a PR for it or would you prefer to retain authorship and commit yourself?

Again, thank you for the release!

**Comment by jkeifer** [comment]
You're welcome!

I just double checked and I see that change in there, in views.py on lines 103 - 114 and 263. Are you having a problem with that new behavior not working?

**Comment by ericswpark** [comment]
I have no idea how I missed the new code in there. Sorry about that :o I'll add it to my project and see if it works. Thanks!
